// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpOMatic.Engine.Repository;

#nullable disable

namespace SharpOMatic.Engine.Sqlite.Migrations
{
    [DbContext(typeof(SharpOMaticDbContext))]
    [Migration("20260414123000_RestoreToolCallId")]
    partial class RestoreToolCallId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SharpOMatic")
                .HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Asset", b =>
                {
                    b.Property<Guid>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AssetId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("FolderId");

                    b.HasIndex("Name");

                    b.HasIndex("RunId");

                    b.HasIndex("Scope", "Created");

                    b.HasIndex("Scope", "FolderId", "Created");

                    b.ToTable("Assets", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.AssetFolder", b =>
                {
                    b.Property<Guid>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FolderId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssetFolders", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.ConnectorConfigMetadata", b =>
                {
                    b.Property<string>("ConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConfigId");

                    b.ToTable("ConnectorConfigMetadata", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.ConnectorMetadata", b =>
                {
                    b.Property<Guid>("ConnectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConnectorId");

                    b.ToTable("ConnectorMetadata", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Conversation", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentTurnNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseExpires")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("ConversationId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Conversations", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.ConversationCheckpoint", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckpointCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GosubStackJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResumeMode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ResumeNodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeStateJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowSnapshotsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("ConversationId");

                    b.ToTable("ConversationCheckpoints", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalColumn", b =>
                {
                    b.Property<Guid>("EvalColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntryType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EvalConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Optional")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("EvalColumnId");

                    b.HasIndex("EvalConfigId");

                    b.ToTable("EvalColumns", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalConfig", b =>
                {
                    b.Property<Guid>("EvalConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxParallel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowScoreMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunScoreMode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("EvalConfigId");

                    b.ToTable("EvalConfigs", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalData", b =>
                {
                    b.Property<Guid>("EvalDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DoubleValue")
                        .HasColumnType("REAL");

                    b.Property<Guid>("EvalColumnId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvalRowId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IntValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StringValue")
                        .HasColumnType("TEXT");

                    b.HasKey("EvalDataId");

                    b.HasIndex("EvalColumnId");

                    b.HasIndex("EvalRowId");

                    b.ToTable("EvalData", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalGrader", b =>
                {
                    b.Property<Guid>("EvalGraderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvalConfigId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeInScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PassThreshold")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("EvalGraderId");

                    b.HasIndex("EvalConfigId");

                    b.ToTable("EvalGraders", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRow", b =>
                {
                    b.Property<Guid>("EvalRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvalConfigId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("EvalRowId");

                    b.HasIndex("EvalConfigId");

                    b.ToTable("EvalRows", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRun", b =>
                {
                    b.Property<Guid>("EvalRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AveragePassRate")
                        .HasColumnType("REAL");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvalConfigId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedRows")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunScoreMode")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Started")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.HasKey("EvalRunId");

                    b.HasIndex("EvalConfigId", "Order")
                        .IsUnique();

                    b.ToTable("EvalRuns", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRunGraderSummary", b =>
                {
                    b.Property<Guid>("EvalRunGraderSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AverageScore")
                        .HasColumnType("REAL");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EvalGraderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvalRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxScore")
                        .HasColumnType("REAL");

                    b.Property<double?>("MedianScore")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinScore")
                        .HasColumnType("REAL");

                    b.Property<double?>("PassRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("StandardDeviation")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("EvalRunGraderSummaryId");

                    b.HasIndex("EvalGraderId");

                    b.HasIndex("EvalRunId");

                    b.ToTable("EvalRunGraderSummaries", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRunRow", b =>
                {
                    b.Property<Guid>("EvalRunRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvalRowId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvalRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputContext")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputContext")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Started")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("EvalRunRowId");

                    b.HasIndex("EvalRowId");

                    b.HasIndex("EvalRunId");

                    b.ToTable("EvalRunRows", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRunRowGrader", b =>
                {
                    b.Property<Guid>("EvalRunRowGraderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvalGraderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvalRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvalRunRowId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputContext")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputContext")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Started")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("EvalRunRowGraderId");

                    b.HasIndex("EvalGraderId");

                    b.HasIndex("EvalRunRowId");

                    b.ToTable("EvalRunRowGraders", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Information", b =>
                {
                    b.Property<Guid>("InformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("InformationType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("TEXT");

                    b.HasKey("InformationId");

                    b.HasIndex("TraceId", "Created");

                    b.ToTable("Informations", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.ModelConfigMetadata", b =>
                {
                    b.Property<string>("ConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConfigId");

                    b.ToTable("ModelConfigMetadata", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.ModelMetadata", b =>
                {
                    b.Property<Guid>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModelId");

                    b.ToTable("ModelMetadata", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Run", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputContext")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputEntries")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsEditorEvents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputContext")
                        .HasColumnType("TEXT");

                    b.Property<int>("RunStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Stopped")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TurnNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("RunId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("WorkflowId", "Created");

                    b.HasIndex("WorkflowId", "RunStatus");

                    b.ToTable("Runs", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Setting", b =>
                {
                    b.Property<Guid>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SettingType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UserEditable")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ValueBoolean")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ValueDouble")
                        .HasColumnType("REAL");

                    b.Property<int?>("ValueInteger")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueString")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingId");

                    b.ToTable("Settings", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.StreamEvent", b =>
                {
                    b.Property<Guid>("StreamEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MessageRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentMessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextDelta")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("StreamEventId");

                    b.HasIndex("ConversationId", "SequenceNumber");

                    b.HasIndex("RunId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("WorkflowId", "Created");

                    b.ToTable("StreamEvents", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Trace", b =>
                {
                    b.Property<Guid>("TraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputContext")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NodeEntityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputContext")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentTraceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("TraceId");

                    b.HasIndex("RunId", "Created");

                    b.ToTable("Traces", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Workflow", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Connections")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConversationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Named")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nodes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkflowId");

                    b.ToTable("Workflows", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Asset", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SharpOMatic.Engine.Repository.AssetFolder", null)
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SharpOMatic.Engine.Repository.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Conversation", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.Workflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.ConversationCheckpoint", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalColumn", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalConfig", null)
                        .WithMany()
                        .HasForeignKey("EvalConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalData", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalColumn", null)
                        .WithMany()
                        .HasForeignKey("EvalColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpOMatic.Engine.Repository.EvalRow", null)
                        .WithMany()
                        .HasForeignKey("EvalRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalGrader", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalConfig", null)
                        .WithMany()
                        .HasForeignKey("EvalConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRow", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalConfig", null)
                        .WithMany()
                        .HasForeignKey("EvalConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRun", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalConfig", null)
                        .WithMany()
                        .HasForeignKey("EvalConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRunGraderSummary", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalGrader", null)
                        .WithMany()
                        .HasForeignKey("EvalGraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpOMatic.Engine.Repository.EvalRun", null)
                        .WithMany()
                        .HasForeignKey("EvalRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRunRow", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalRow", null)
                        .WithMany()
                        .HasForeignKey("EvalRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpOMatic.Engine.Repository.EvalRun", null)
                        .WithMany()
                        .HasForeignKey("EvalRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRunRowGrader", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalGrader", null)
                        .WithMany()
                        .HasForeignKey("EvalGraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpOMatic.Engine.Repository.EvalRunRow", null)
                        .WithMany()
                        .HasForeignKey("EvalRunRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Run", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SharpOMatic.Engine.Repository.Workflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.StreamEvent", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Trace", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
