// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpOMatic.Engine.Repository;

#nullable disable

namespace SharpOMatic.Engine.SqlServer.Migrations
{
    [DbContext(typeof(SharpOMaticDbContext))]
    [Migration("20260215103000_AddEvalRunCancelAndRunRowOrder")]
    partial class AddEvalRunCancelAndRunRowOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SharpOMatic")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Asset", b =>
                {
                    b.Property<Guid>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetId");

                    b.HasIndex("Name");

                    b.HasIndex("RunId");

                    b.HasIndex("Scope", "Created");

                    b.ToTable("Assets", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.ConnectorConfigMetadata", b =>
                {
                    b.Property<string>("ConfigId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("ConfigId");

                    b.ToTable("ConnectorConfigMetadata", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.ConnectorMetadata", b =>
                {
                    b.Property<Guid>("ConnectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("ConnectorId");

                    b.ToTable("ConnectorMetadata", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalColumn", b =>
                {
                    b.Property<Guid>("EvalColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EntryType")
                        .HasColumnType("int");

                    b.Property<Guid>("EvalConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InputPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Optional")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("EvalColumnId");

                    b.HasIndex("EvalConfigId");

                    b.ToTable("EvalColumns", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalConfig", b =>
                {
                    b.Property<Guid>("EvalConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParallel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EvalConfigId");

                    b.ToTable("EvalConfigs", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalData", b =>
                {
                    b.Property<Guid>("EvalDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("bit");

                    b.Property<double?>("DoubleValue")
                        .HasColumnType("float");

                    b.Property<Guid>("EvalColumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvalRowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IntValue")
                        .HasColumnType("int");

                    b.Property<string>("StringValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvalDataId");

                    b.HasIndex("EvalColumnId");

                    b.HasIndex("EvalRowId");

                    b.ToTable("EvalData", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalGrader", b =>
                {
                    b.Property<Guid>("EvalGraderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvalConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<double>("PassThreshold")
                        .HasColumnType("float");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EvalGraderId");

                    b.HasIndex("EvalConfigId");

                    b.ToTable("EvalGraders", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRow", b =>
                {
                    b.Property<Guid>("EvalRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvalConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("EvalRowId");

                    b.HasIndex("EvalConfigId");

                    b.ToTable("EvalRows", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRun", b =>
                {
                    b.Property<Guid>("EvalRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("bit");

                    b.Property<int>("CompletedRows")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EvalConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FailedRows")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.HasKey("EvalRunId");

                    b.HasIndex("EvalConfigId");

                    b.ToTable("EvalRuns", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRunGraderSummary", b =>
                {
                    b.Property<Guid>("EvalRunGraderSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AverageScore")
                        .HasColumnType("float");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("EvalGraderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvalRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<double?>("MaxScore")
                        .HasColumnType("float");

                    b.Property<double?>("MedianScore")
                        .HasColumnType("float");

                    b.Property<double?>("MinScore")
                        .HasColumnType("float");

                    b.Property<double?>("PassRate")
                        .HasColumnType("float");

                    b.Property<double?>("StandardDeviation")
                        .HasColumnType("float");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.HasKey("EvalRunGraderSummaryId");

                    b.HasIndex("EvalGraderId");

                    b.HasIndex("EvalRunId");

                    b.ToTable("EvalRunGraderSummaries", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRunRow", b =>
                {
                    b.Property<Guid>("EvalRunRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EvalRowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvalRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("OutputContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("EvalRunRowId");

                    b.HasIndex("EvalRowId");

                    b.HasIndex("EvalRunId");

                    b.ToTable("EvalRunRows", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRunRowGrader", b =>
                {
                    b.Property<Guid>("EvalRunRowGraderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EvalGraderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvalRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvalRunRowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutputContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("EvalRunRowGraderId");

                    b.HasIndex("EvalGraderId");

                    b.HasIndex("EvalRunRowId");

                    b.ToTable("EvalRunRowGraders", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.ModelConfigMetadata", b =>
                {
                    b.Property<string>("ConfigId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("ConfigId");

                    b.ToTable("ModelConfigMetadata", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.ModelMetadata", b =>
                {
                    b.Property<Guid>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("ModelId");

                    b.ToTable("ModelMetadata", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Run", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputEntries")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RunStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Stopped")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RunId");

                    b.HasIndex("WorkflowId", "Created");

                    b.HasIndex("WorkflowId", "RunStatus");

                    b.ToTable("Runs", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Setting", b =>
                {
                    b.Property<Guid>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SettingType")
                        .HasColumnType("int");

                    b.Property<bool>("UserEditable")
                        .HasColumnType("bit");

                    b.Property<bool?>("ValueBoolean")
                        .HasColumnType("bit");

                    b.Property<double?>("ValueDouble")
                        .HasColumnType("float");

                    b.Property<int?>("ValueInteger")
                        .HasColumnType("int");

                    b.Property<string>("ValueString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingId");

                    b.ToTable("Settings", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Trace", b =>
                {
                    b.Property<Guid>("TraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("datetime2");

                    b.Property<string>("InputContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NodeEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NodeStatus")
                        .HasColumnType("int");

                    b.Property<int>("NodeType")
                        .HasColumnType("int");

                    b.Property<string>("OutputContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentTraceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ThreadId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TraceId");

                    b.HasIndex("RunId", "Created");

                    b.ToTable("Traces", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Workflow", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Connections")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Named")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nodes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("WorkflowId");

                    b.ToTable("Workflows", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Asset", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalColumn", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalConfig", null)
                        .WithMany()
                        .HasForeignKey("EvalConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalData", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalColumn", null)
                        .WithMany()
                        .HasForeignKey("EvalColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpOMatic.Engine.Repository.EvalRow", null)
                        .WithMany()
                        .HasForeignKey("EvalRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalGrader", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalConfig", null)
                        .WithMany()
                        .HasForeignKey("EvalConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRow", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalConfig", null)
                        .WithMany()
                        .HasForeignKey("EvalConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRun", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalConfig", null)
                        .WithMany()
                        .HasForeignKey("EvalConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRunGraderSummary", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalGrader", null)
                        .WithMany()
                        .HasForeignKey("EvalGraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpOMatic.Engine.Repository.EvalRun", null)
                        .WithMany()
                        .HasForeignKey("EvalRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRunRow", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalRow", null)
                        .WithMany()
                        .HasForeignKey("EvalRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpOMatic.Engine.Repository.EvalRun", null)
                        .WithMany()
                        .HasForeignKey("EvalRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.EvalRunRowGrader", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.EvalGrader", null)
                        .WithMany()
                        .HasForeignKey("EvalGraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpOMatic.Engine.Repository.EvalRunRow", null)
                        .WithMany()
                        .HasForeignKey("EvalRunRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Run", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.Workflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Trace", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
