// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SharpOMatic.Engine.Repository;

#nullable disable

namespace SharpOMatic.Engine.SqlServer.Migrations
{
    [DbContext(typeof(SharpOMaticDbContext))]
    [Migration("20260710000000_EvalRowRepeat")]
    partial class EvalRowRepeat
    {
    }
}
