// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpOMatic.Engine.Repository;

#nullable disable

namespace SharpOMatic.Engine.Migrations
{
    [DbContext(typeof(SharpOMaticDbContext))]
    partial class SharpOMaticDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SharpOMatic")
                .HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Asset", b =>
                {
                    b.Property<Guid>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AssetId");

                    b.HasIndex("Name");

                    b.HasIndex("RunId");

                    b.HasIndex("Scope", "Created");

                    b.ToTable("Assets", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.ConnectorConfigMetadata", b =>
                {
                    b.Property<string>("ConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConfigId");

                    b.ToTable("ConnectorConfigMetadata", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.ConnectorMetadata", b =>
                {
                    b.Property<Guid>("ConnectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConnectorId");

                    b.ToTable("ConnectorMetadata", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.ModelConfigMetadata", b =>
                {
                    b.Property<string>("ConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConfigId");

                    b.ToTable("ModelConfigMetadata", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.ModelMetadata", b =>
                {
                    b.Property<Guid>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModelId");

                    b.ToTable("ModelMetadata", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Run", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputContext")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputEntries")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputContext")
                        .HasColumnType("TEXT");

                    b.Property<int>("RunStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Stopped")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("RunId");

                    b.HasIndex("WorkflowId", "Created");

                    b.HasIndex("WorkflowId", "RunStatus");

                    b.ToTable("Runs", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Setting", b =>
                {
                    b.Property<Guid>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SettingType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UserEditable")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ValueBoolean")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ValueDouble")
                        .HasColumnType("REAL");

                    b.Property<int?>("ValueInteger")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueString")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingId");

                    b.ToTable("Settings", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Trace", b =>
                {
                    b.Property<Guid>("TraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputContext")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NodeEntityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputContext")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentNodeEntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("TraceId");

                    b.HasIndex("RunId", "Created");

                    b.ToTable("Traces", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Workflow", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Connections")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Named")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nodes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkflowId");

                    b.ToTable("Workflows", "SharpOMatic");
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Asset", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Run", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.Workflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpOMatic.Engine.Repository.Trace", b =>
                {
                    b.HasOne("SharpOMatic.Engine.Repository.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
